spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379


server:
  port: 8089
